

export const MANAGER_SIGNIN_REQUEST = 'MANAGER_SIGNIN_REQUEST';
export const MANAGER_SIGNIN_SUCCESS = 'MANAGER_SIGNIN_SUCCESS';
export const MANAGER_SIGNIN_FAIL = 'MANAGER_SIGNIN_FAIL';

export const MANAGER_SIGNOUT = 'MANAGER_SIGNOUT';
